![Logo de NumPy](https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/numpy_logo.png?raw=true)

## Introducción a NumPy

`NumPy` es un juego de palabras que significa **Python numérico** (*Numerical Python*). Es una librería de código abierto que se utiliza para llevar a cabo tareas matemáticas con altísima eficiencia. Además, introduce estructuras de datos como los arrays multidimensionales, que se pueden operar entre ellos a alto nivel, sin meterse mucho en el detalle.

En concreto, las claves de esta librería son:

- **Array multidimensionales**: Esta librería proporciona un objeto llamado `ndarray`, que permite almacenar y manipular grandes conjuntos de datos de forma eficiente. Los arrays pueden tener cualquier número de dimensiones.
- **Operaciones Vectorizadas**: NumPy permite realizar operaciones matemáticas en arrays completos sin la necesidad de bucles explícitos en el código, lo que lo hace muy rápido y eficiente.
- **Funciones matemáticas**: NumPy proporciona una amplia gama de funciones matemáticas para trabajar con arrays, incluyendo funciones trigonométricas, estadísticas, álgebra lineal, entre otras.
- **Eficiencia**: Es mucho más rápido que la misma funcionalidad implementada directamente sobre Python nativo. Además, es muy flexible en términos de acceso y manipulación de elementos individuales o subconjuntos de arrays.

NumPy es una biblioteca fundamental para el Machine Learning y la ciencia de los datos en Python. Proporciona una amplia gama de herramientas y funciones para trabajar eficientemente con datos numéricos en forma de arrays y matrices.

### Arrays

Un **array** de NumPy es una estructura de datos que permite almacenar una colección de elementos, generalmente números, en una o más dimensiones.

#### Array unidimensional

Un array unidimensional (1D) de NumPy es una estructura de datos que contiene una secuencia de elementos en una única dimensión. Es similar a una lista en Python, pero con las ventajas de rendimiento y funcionalidad que ofrece NumPy.

![Array de una dimensión](https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/1D.png?raw=true "1D")

Un array 1D puede ser creado usando la función `array` de la librería con una lista de elementos como argumento. Por ejemplo:

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

Esto creará un array 1D con los elementos 1, 2, 3, 4 y 5. Los elementos del array deben ser del mismo tipo de datos. Si los elementos son de diferentes tipos, NumPy intentará convertirlos al mismo tipo si es posible.

En un array 1D, podemos acceder a los elementos usando **índices** (*indexes*), modificarlos y realizar operaciones matemáticas en el array completo de forma eficiente. A continuación se muestran algunas operaciones que se pueden realizar utilizando el array anterior:

In [ ]:
# Acceder al tercer elemento
print(array[2])

# Cambiar el valor del segundo elemento
array[1] = 7
print(array)

# Sumar 10 a todos los elementos
array += 10
print(array)

# Calcular la suma de los elementos
sum_all = np.sum(array)
print(sum_all)

3
[1 7 3 4 5]
[11 17 13 14 15]
70


#### Array N-dimensional

Un array multidimensional o n-dimensional en NumPy es una estructura de datos que organiza elementos en múltiples dimensiones (ejes). Estos arrays permiten representar estructuras de datos más complejas, como matrices (array 2D, 2 ejes), tensores (array 3D, 3 ejes) y estructuras de mayor dimensión.

![Arrays de diferentes dimensiones](https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/3D.png?raw=true "3D")

Un array N-dimensional puede ser creado también usando la función `array` de la librería. Por ejemplo, si queremos crear un array 2D:

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Si ahora quisiéramos crear un array 3D, tendríamos que pensar en él como una lista de matrices:

In [ ]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Al igual que sucedía con los arrays 1D, los elementos en un array multidimensional son accesibles mediante índices, se pueden realizar operaciones con ellos, etcétera.

A medida que agregamos más dimensiones, el principio básico sigue siendo el mismo: cada dimensión adicional puede considerarse como un nivel adicional de anidamiento. Sin embargo, a nivel práctico, trabajar con arrays de más de 3 o 4 dimensiones puede volverse más complejo y menos intuitivo.

Los arrays n-dimensionales en NumPy permiten una gran flexibilidad y potencia para representar y manipular datos en formas más complejas, especialmente útiles en campos como la ciencia de los datos, procesamiento de imágenes y aprendizaje profundo.

### Funciones

NumPy proporciona una gran cantidad de funciones predefinidas y que se pueden aplicar directamente sobre las estructuras de datos vistas anteriormente o las propias de Python (listas, matrices, etcétera). Algunas de las más utilizadas en el análisis de datos son:

In [ ]:
import numpy as np

# Crear un array para el ejemplo
arr = np.array([1, 2, 3, 4, 5])

# Operaciones Aritméticas
print("Suma:", np.add(arr, 5))
print("Producto:", np.multiply(arr, 3))

# Logarítmicas y Exponenciales
print("Logaritmo natural:", np.log(arr))
print("Exponencial:", np.exp(arr))

# Funciones Estadísticas
print("Media:", np.mean(arr))
print("Mediana:", np.median(arr))
print("Desviación estándar:", np.std(arr))
print("Varianza:", np.var(arr))
print("Máximo valor:", np.max(arr))
print("Índice del máximo valor:", np.argmax(arr))
print("Mínimo valor:", np.min(arr))
print("Índice del mínimo valor:", np.argmin(arr))
print("Suma de todos los elementos:", np.sum(arr))

# Funciones de Redondeo
arr_decimal = np.array([1.23, 2.47, 3.56, 4.89])
print("Redondeo:", np.around(arr_decimal))
print("Entero menor (floor):", np.floor(arr_decimal))
print("Entero mayor (ceil):", np.ceil(arr_decimal))

Suma: [ 6  7  8  9 10]
Producto: [ 3  6  9 12 15]
Logaritmo natural: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Exponencial: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Media: 3.0
Mediana: 3.0
Desviación estándar: 1.4142135623730951
Varianza: 2.0
Máximo valor: 5
Índice del máximo valor: 4
Mínimo valor: 1
Índice del mínimo valor: 0
Suma de todos los elementos: 15
Redondeo: [1. 2. 4. 5.]
Entero menor (floor): [1. 2. 3. 4.]
Entero mayor (ceil): [2. 3. 4. 5.]


## Ejercicios: Haz clic en "open in colab" para realizarlos

> Solución: https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/02.1-Intro-to-Numpy_solutions.ipynb

### Creación de arrays

#### Ejercicio 01:  Crea un **vector nulo** (*null vector*) que tenga 10 elementos (★☆☆)

Un vector nulo es un array de una dimensión compuesto por ceros (`0`).

> NOTA: Revisa la función `np.zeros` (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

In [1]:
import numpy as np

vector_nulo = np.zeros(10)
print(vector_nulo)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Ejercicio 02: Crea un vector de unos que tenga 10 elementos (★☆☆)

> NOTA: Revisa la función `np.ones` (https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [2]:
import numpy as np

vector_normal = np.ones(10)
print(vector_normal)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Ejercicio 03: Investiga la función `linspace` de NumPy y crea un array que contenga 10 elementos (★☆☆)

> NOTA: Revisa la función `np.linspace` (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [3]:
import numpy as np


array_linspace = np.linspace(0, 9, 10)

print(array_linspace)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### Ejercicio 04: Busca varias formas de generar un array con números aleatorios y crea un array 1D y dos arrays 2D (★★☆)

> NOTA: Revisa las funciones `np.random.rand` (https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html), `np.random.randint` (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html) y `np.random.randn` (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html)

In [19]:
import numpy as np


array_1d = np.random.randint(0, 5, 6)
print("Array 1D con números enteros aleatorios:\n", array_1d)

array_2d_1 = np.random.randint(0, 10, (3, 3))
print("\nPrimer Array 2D con números enteros aleatorios:\n", array_2d_1)

array_2d_2 = np.random.randint(10, 100, (4, 4))
print("\nSegundo Array 2D con números enteros aleatorios:\n", array_2d_2)


Array 1D con números enteros aleatorios:
 [2 2 1 2 2 4]

Primer Array 2D con números enteros aleatorios:
 [[6 9 2]
 [0 9 7]
 [4 0 1]]

Segundo Array 2D con números enteros aleatorios:
 [[21 83 93 80]
 [11 24 46 56]
 [83 93 93 68]
 [30 18 28 39]]


#### Ejercicio 05: Crea una matriz (array 2D) identidad de 5x5 (★☆☆)


> NOTA: Revisa la función `np.eye`(https://numpy.org/devdocs/reference/generated/numpy.eye.html)

In [22]:
array_2d = np.random.randint(10, 100, (5, 5))
print("\nMatriz de 5x5 2d valores:\n", array_2d_2)

import numpy as np

# Crear una matriz identidad  de 5x5
matriz_identidad = np.eye(5)
print("Matriz Identidad 5x5:\n", matriz_identidad)


Matriz de 5x5 2d valores:
 [[21 83 93 80]
 [11 24 46 56]
 [83 93 93 68]
 [30 18 28 39]]
Matriz Identidad 5x5:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### Ejercicio 06: Crea una matriz con números aleatorios de 3x2 y calcula el valor mínimo y máximo (★☆☆)

> NOTA: Revisa la función `np.min` (https://numpy.org/devdocs/reference/generated/numpy.min.html) y `np.max` (https://numpy.org/devdocs/reference/generated/numpy.max.html)

In [27]:
import numpy as np

# Crear una matriz 3x2 con números enteros aleatorios entre 1 y 100
matriz_3x2 = np.random.randint(1, 101, size=(3, 2))
print("Matriz 3x2 con números enteros aleatorios:\n", matriz_3x2_enteros)

# Calcular el valor mínimo y máximo
valor_minimo = matriz_3x2_enteros.min()
valor_maximo = matriz_3x2_enteros.max()

print("\nValor mínimo:", valor_minimo)
print("Valor máximo:", valor_maximo)

Matriz 3x2 con números enteros aleatorios:
 [[24 22]
 [88 63]
 [52 11]]

Valor mínimo: 11
Valor máximo: 88


#### Ejercicio 07: Crea un vector con números aleatorios de 30 elementos y calcula la media (★☆☆)

> NOTA: Revisa la función `np.mean` (https://numpy.org/doc/stable/reference/generated/numpy.mean.html)

In [30]:
import numpy as np

vector_30 = np.random.randint(0, 100, 30)

media = vector_30.mean()

print(vector_30)

print("\nLa media del vector de 30 valores es:",media)

[ 8 69 91 78 23 43 21 21 58 52 81 26 68 22 67 83 64 19  8 17 65 48 96  3
 95 40  4 47 55  0]

La media del vector de 30 valores es: 45.733333333333334


#### Ejercicio 08: Convierte la lista `[1, 2, 3]` y la tupla `(1, 2, 3)` en arrays (★☆☆)

In [31]:
import numpy as np

# Convertir la lista [1, 2, 3] en un array
lista = [1, 2, 3]
array_desde_lista = np.array(lista)

# Convertir la tupla (1, 2, 3) en un array
tupla = (1, 2, 3)
array_desde_tupla = np.array(tupla)

print("Array desde lista:", array_desde_lista)
print("Array desde tupla:", array_desde_tupla)

Array desde lista: [1 2 3]
Array desde tupla: [1 2 3]


### Operaciones entre arrays

#### Ejercicio 09: Invierte el vector del ejercicio anterior (★☆☆)

> NOTA: Revisa la función `np.flip` (https://numpy.org/doc/stable/reference/generated/numpy.flip.html)

In [33]:
import numpy as np

vector_original = np.array([1, 2, 3])

vector_invertido = np.flip(vector_original)

print("Vector original:", vector_original)
print("Vector invertido:", vector_invertido)

Vector original: [1 2 3]
Vector invertido: [3 2 1]


#### Ejercicio 10: Cambia el tamaño de un array aleatorio de dimensiones 5x12 en 12x5 (★☆☆)

> NOTA: Revisa la función `np.reshape` (https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [2]:
import numpy as np

array_aleatorio = np.random.randint(low=0, high=100, size=(5, 12))

array_redimensionado = np.reshape(array_aleatorio, (12, 5))

print("Array original de dimensiones 5x12:\n", array_aleatorio)
print("\nArray redimensionado a 12x5:\n", array_redimensionado)


Array original de dimensiones 5x12:
 [[70 19  5 30  2  4 36 13 26 76 40 49]
 [33 54 26 27 21 64 33 35 63 13 35 34]
 [92 78 45 78 42 55 21 21 93 55 66 72]
 [20 30  7  6  9 91  8 27  6 65 44 15]
 [82 39 56 36 14 59 40 75 95 99 95 17]]

Array redimensionado a 12x5:
 [[70 19  5 30  2]
 [ 4 36 13 26 76]
 [40 49 33 54 26]
 [27 21 64 33 35]
 [63 13 35 34 92]
 [78 45 78 42 55]
 [21 21 93 55 66]
 [72 20 30  7  6]
 [ 9 91  8 27  6]
 [65 44 15 82 39]
 [56 36 14 59 40]
 [75 95 99 95 17]]


#### Ejercicio 11: Convierte la lista `[1, 2, 0, 0, 4, 0]` en un array y obtén el índice de los elementos que no son cero (★★☆)

> NOTA: Revisa la función `np.where` (https://numpy.org/devdocs/reference/generated/numpy.where.html)

In [1]:
import numpy as np

lista = [1, 2, 0, 0, 4, 0]
array_lista = np.array(lista)

indices_no_cero = np.where(array_lista != 0)[0]

print("Índices de los elementos que no son cero:", indices_no_cero)



Índices de los elementos que no son cero: [0 1 4]


#### Ejercicio 12: Convierte la lista `[0, 5, -1, 3, 15]` en un array, multiplica sus valores por `-2` y obtén los elementos pares (★★☆)

In [2]:
import numpy as np

lista = [0, 5, -1, 3, 15]
array_lista = np.array(lista)

array_modificado = array_lista * -2

elementos_pares = array_modificado[array_modificado % 2 == 0]

print("Elementos pares después de multiplicar por -2:", elementos_pares)


Elementos pares después de multiplicar por -2: [  0 -10   2  -6 -30]


#### Ejercicio 13: Crea un vector aleatorio de 10 elementos y ordénalo de menor a mayor (★★☆)

> NOTA: Revisa la función `np.sort` (https://numpy.org/doc/stable/reference/generated/numpy.sort.html)

In [4]:
import numpy as np

vector_aleatorio = np.random.randint(0, 100, 10)

vector_ordenado = np.sort(vector_aleatorio)

print("Vector aleatorio:", vector_aleatorio)
print("Vector ordenado de menor a mayor:", vector_ordenado)


Vector aleatorio: [74  3 66  4 72 11 60 77 86 42]
Vector ordenado de menor a mayor: [ 3  4 11 42 60 66 72 74 77 86]


#### Ejercicio 14: Genera dos vectores aleatorios de 8 elementos y aplica las operaciones de suma, resta y multiplicación entre ellos (★★☆)

> NOTA: Revisa las funciones matemáticas: https://numpy.org/doc/stable/reference/routines.math.html

In [6]:
import numpy as np

vector_1 = np.random.randint(0, 10, 8)
vector_2 = np.random.randint(0, 10, 8)


suma = vector_1 + vector_2
resta = vector_1 - vector_2
multiplicacion = vector_1 * vector_2

print("Vector 1:", vector_1)
print("Vector 2:", vector_2)
print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)


Vector 1: [3 4 4 0 9 6 3 1]
Vector 2: [9 3 6 1 3 3 5 9]
Suma: [12  7 10  1 12  9  8 10]
Resta: [-6  1 -2 -1  6  3 -2 -8]
Multiplicación: [27 12 24  0 27 18 15  9]


#### Ejercicio 15: Convierte la lista `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]` en un array y transfórmalo en una matriz con filas de 3 columnas (★★★)

In [8]:
import numpy as np

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
array_lista = np.array(lista)

# el -1 indica al codigo que calcule automaticamente el numero de filas en base las columnas
matriz = np.reshape(array_lista, (-1, 3))

print("Matriz resultante con filas de 3 columnas:\n", matriz)


Matriz resultante con filas de 3 columnas:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
